A: Agilent Technologies
AAL: American Airlines
AAPL: Apple Inc.
ABBV: AbbVie
ABNB: Airbnb
ABT: Abbott Laboratories
ACGL: Arch Capital Group
ACN: Accenture
ADBE: Adobe Inc.
ADI: Analog Devices
ADM: Archer Daniels Midland
ADSK: Autodesk
AEE: Ameren
AEP: American Electric Power
AES: AES
AFL: Aflac
AIZ: Assurant
AJG: Arthur J. Gallagher & Co.
AKAM: Akamai Technologies
ALB: Albemarle Corporation
ALGN: Align Technology
ALL: Allstate
ALLE: Allegion
AMAT: Applied Materials
AMCR: Amcor
AMD: Advanced Micro Devices
AME: Ametek
AMGN: Amgen
AMP: Ameriprise Financial
AMT: American Tower
AMZN: Amazon.com
AOS: A. O. Smith
APA: APA Corporation
APH: Amphenol
APTV: Aptiv
ARE: Alexandria Real Estate Equities
ARM: Arm
ASML: ASML Holding
ATO: Atmos Energy
AVB: AvalonBay Communities
AVGO: Broadcom Inc.
AVY: Avery Dennison
AWK: American Water Works
AXP: American Express
AZN: AstraZeneca
AZO: AutoZone
BA: The Boeing Company
BAC: Bank of America
BAX: Baxter International
BBWI: Bath & Body Works, Inc.
BBY: Best Buy
BIIB: Biogen
BIO: Bio-Rad Laboratories
BKR: Baker Hughes
BLK: BlackRock
BMY: Bristol Myers Squibb
BR: Broadridge Financial Solutions
BRO: Brown & Brown
BSX: Boston Scientific
BWA: BorgWarner
C: Citigroup
CAG: Conagra Brands
CAH: Cardinal Health
CARR: Carrier Global
CAT: Caterpillar Inc.
CB: Chubb Limited
CBOE: Cboe Global Markets
CCEP: Coca-Cola Europacific Partners
CCI: Crown Castle
CCL: Carnival
CDNS: Cadence Design Systems
CDW: CDW
CE: Celanese
CEG: Constellation Energy
CF: CF Industries
CFG: Citizens Financial Group
CHD: Church & Dwight
CHTR: Charter Communications
CI: Cigna
CINF: Cincinnati Financial
CL: Colgate-Palmolive
CLX: Clorox
CMCSA: Comcast
CMG: Chipotle Mexican Grill
CMI: Cummins
CMS: CMS Energy
CNC: Centene Corporation
CNP: CenterPoint Energy
COO: The Cooper Companies
COP: ConocoPhillips
COR: Cencora
COST: Costco Wholesale
CPRT: Copart
CPT: Camden Property Trust
CRM: Salesforce
CRWD: CrowdStrike
CSCO: Cisco Systems
CSX: CSX Corporation
CTAS: Cintas
CTVA: Corteva
CVS: CVS Health
CVX: Chevron Corporation
CZR: Caesars Entertainment
D: Dominion Energy
DAL: Delta Air Lines
DASH: DoorDash
DDOG: Datadog
DECK: Deckers Outdoor Corporation
DG: Dollar General
DGX: Quest Diagnostics
DHR: Danaher Corporation
DIS: The Walt Disney Company
DLTR: Dollar Tree
DOV: Dover Corporation
DOW: Dow Inc.
DPZ: Domino's Pizza
DRI: Darden Restaurants
DTE: DTE Energy
DUK: Duke Energy
DVA: DaVita
DVN: Devon Energy
EA: Electronic Arts
EBAY: EBay
ECL: Ecolab
ED: Consolidated Edison
EFX: Equifax
EIX: Edison International
EL: Estée Lauder Companies
EMN: Eastman Chemical Company
EMR: Emerson Electric
ENPH: Enphase Energy
EOG: EOG Resources
EPAM: EPAM Systems
EQIX: Equinix
EQR: Equity Residential
EQT: EQT Corporation
ES: Eversource Energy
ETR: Entergy
EVRG: Evergy
EW: Edwards Lifesciences
EXC: Exelon
EXPE: Expedia
EXR: Extra Space Storage
F: Ford Motor Company
FANG: Diamondback Energy
FAST: Fastenal
FCNCA: First Citizens BancShares
FCX: Freeport-McMoRan
FDX: FedEx Corporation
FE: FirstEnergy
FFIV: F5, Inc.
FISV: Fiserv
FMC: FMC Corporation
FOX: Fox Corporation
FOXA: Fox Corporation
FSLR: First Solar
FTNT: Fortinet
FTV: Fortive
GD: General Dynamics
GDDY: GoDaddy
GE: GE Aerospace
GEN: Gen Digital
GFS: GlobalFoundries
GILD: Gilead Sciences
GIS: General Mills
GL: Globe Life
GM: General Motors
GNRC: Generac
GOOG: Alphabet Inc.
GOOGL: Alphabet Inc.
GPC: Genuine Parts Company
GPN: Global Payments
GRMN: Garmin
GS: Goldman Sachs
HAL: Halliburton
HAS: Hasbro
HBAN: Huntington Bancshares
HCA: HCA Healthcare
HD: Home Depot
HOLX: Hologic
HPE: Hewlett Packard Enterprise
HPQ: HP Inc.
HRL: Hormel Foods
HSIC: Henry Schein
HST: Host Hotels & Resorts
HSY: The Hershey Company
HUBB: Hubbell Incorporated
HUM: Humana
HWM: Howmet Aerospace
ICE: Intercontinental Exchange
IDXX: Idexx Laboratories
IEX: IDEX Corporation
IFF: International Flavors & Fragrances
ILMN: Illumina, Inc.
INCY: Incyte
INTC: Intel Corporation
INTU: Intuit
INVH: Invitation Homes
IP: International Paper
IQV: IQVIA
IR: Ingersoll Rand
ISRG: Intuitive Surgical
IT: Gartner
ITW: Illinois Tool Works
IVZ: Invesco
J: Jacobs Solutions
JBL: Jabil
JKHY: Jack Henry & Associates
JNJ: Johnson & Johnson
JPM: JPMorgan Chase
KDP: Keurig Dr Pepper
KHC: Kraft Heinz
KIM: Kimco Realty
KLAC: KLA Corporation
KMB: Kimberly-Clark
KMI: Kinder Morgan
KMX: CarMax
KO: The Coca-Cola Company
KR: Kroger
KVUE: Kenvue
L: Loews Corporation
LDOS: Leidos
LEN: Lennar
LH: Labcorp
LHX: L3Harris Technologies
LIN: Linde plc
LKQ: LKQ Corporation
LLY: Eli Lilly and Company
LNT: Alliant Energy
LRCX: Lam Research
LUV: Southwest Airlines
LVS: Las Vegas Sands
LW: Lamb Weston
LYV: Live Nation Entertainment
MA: Mastercard
MAA: Mid-America Apartment Communities
MAR: Marriott International
MAS: Masco
MCD: McDonald's Corporation
MCHP: Microchip Technology
MCK: McKesson Corporation
MCO: Moody's Corporation
MDB: MongoDB Inc.
MDLZ: Mondelez International
MDT: Medtronic
MELI: Mercado Libre
MET: MetLife
META: Meta Platforms
MGM: MGM Resorts International
MHK: Mohawk Industries
MKC: McCormick & Company
MKTX: MarketAxess
MLM: Martin Marietta Materials
MMM: 3M
MNST: Monster Beverage
MO: Altria
MOH: Molina Healthcare
MOS: The Mosaic Company
MPC: Marathon Petroleum
MPWR: Monolithic Power Systems
MRNA: Moderna
MRVL: Marvell Technology
MS: Morgan Stanley
MSCI: MSCI
MSFT: Microsoft Corporation
MSI: Motorola Solutions
MTB: M&T Bank
MTCH: Match
NCLH: Norwegian Cruise Line
NDAQ: Nasdaq, Inc.
NDSN: Nordson Corporation
NEE: NextEra Energy
NEM: Newmont
NFLX: Netflix, Inc.
NI: NiSource
NKE: Nike, Inc.
NOW: ServiceNow
NRG: NRG Energy
NSC: Norfolk Southern Railway
NTAP: NetApp
NTRS: Northern Trust
NUE: Nucor
NVDA: Nvidia
NVR: NVR, Inc.
NWL: Newell Brands
NWS: News Corporation
NWSA: News Corporation
NXPI: NXP Semiconductors
O: Realty Income
ODFL: Old Dominion Freight Line
OGN: Organon & Co.
OKE: Oneok
OMC: Omnicom Group
'ON': ON Semiconductor
ORCL: Oracle Corporation
OTIS: Otis Worldwide
OXY: Occidental Petroleum
PANW: Palo Alto Networks
PAYX: Paychex
PCAR: Paccar
PEG: Public Service Enterprise Group
PEP: PepsiCo
PFE: Pfizer
PFG: Principal Financial Group
PG: Procter & Gamble
PGR: Progressive
PH: Parker Hannifin
PHM: PulteGroup
PKG: Packaging Corporation of America
PLD: Prologis
PM: Philip Morris International
PNC: PNC Financial Services
PNR: Pentair
PNW: Pinnacle West Capital
POOL: Pool Corporation
PPG: PPG Industries
PPL: PPL Corporation
PRU: Prudential Financial
PSA: Public Storage
PSX: Phillips 66
PVH: PVH Corp.
PWR: Quanta Services
PYPL: PayPal
QCOM: Qualcomm
QRVO: Qorvo
RCL: Royal Caribbean Cruises Ltd.
REG: Regency Centers
REGN: Regeneron Pharmaceuticals
RF: Regions Financial Corporation
RHI: Robert Halfon
RJF: Raymond James Financial
RL: Ralph Lauren Corporation
RMD: ResMed
ROL: Rollins, Inc.
ROP: Roper Technologies
ROST: Ross Stores
RSG: Republic Services
RVTY: Revvity
SBAC: SBA Communications
SBUX: Starbucks
SEE: Sealed Air
SHW: Sherwin-Williams
SJM: The J.M. Smucker Company
SNA: Snap-on
SNPS: Synopsys
SPG: Simon Property Group
SPGI: S&P Global
SRE: Sempra
STE: Steris
STLD: Steel Dynamics
STT: State Street Corporation
STZ: Constellation Brands
SWK: Stanley Black & Decker
SWKS: Skyworks Solutions
SYF: Synchrony Financial
SYK: Stryker Corporation
SYY: Sysco
T: AT&T Inc.
TAP: Molson Coors Beverage Company
TDG: TransDigm Group
TDY: Teledyne Technologies
TEAM: Atlassian
TECH: Bio-Techne
TEL: TE Connectivity
TER: Teradyne
TFC: Truist Financial
TFX: Teleflex
TGT: Target Corporation
TJX: TJX Companies
TMO: Thermo Fisher Scientific
TMUS: T-Mobile US
TPR: Tapestry, Inc.
TRGP: Targa Resources
TRMB: Trimble Inc.
TROW: T. Rowe Price
TSCO: Tractor Supply Company
TSLA: Tesla, Inc.
TSN: Tyson Foods
TT: Trane Technologies
TTD: The Trade Desk
TXN: Texas Instruments
TXT: Textron
TYL: Tyler Technologies
UAL: United Airlines
UHS: Universal Health Services
ULTA: Ulta Beauty
UNH: UnitedHealth Group
UNP: Union Pacific Corporation
UPS: United Parcel Service
URI: United Rentals
USB: U.S. Bancorp
V: Visa Inc.
VICI: Vici Properties
VLO: Valero Energy
VMC: Vulcan Materials Company
VRSK: Verisk Analytics
VRSN: Verisign
VRTX: Vertex Pharmaceuticals
VTRS: Viatris
VZ: Verizon Communications
WAT: Waters Corporation
WBD: Warner Bros. Discovery
WDAY: Workday, Inc.
WEC: WEC Energy Group
WELL: Welltower
WHR: Whirlpool Corporation
WM: Waste management
WMB: Williams Companies
WMT: Walmart
WRB: W. R. Berkley Corporation
WST: West Pharmaceutical Services
WY: Weyerhaeuser
WYNN: Wynn Resorts
XEL: Xcel Energy
XOM: ExxonMobil
XRAY: Dentsply Sirona
XYL: Xylem Inc.
YUM: Yum! Brands
ZBH: Zimmer Biomet
ZBRA: Zebra Technologies
ZS: Zscaler
ZTS: Zoetis
